### ISSUE TITLE
Detailed explanation of How you created data set

### ISSUE THREAD

**Issue by prativadas** [deepankverma/slums_detection#1]
Hi, I have tried the google earth path tool and created the CSV file. but I don't understand how to proceed further like how did you get the corresponding labels to each pair of coordinates.  How did you get VHR satellite image as it's not free?

**Comment by deepankverma** [comment]
The corresponding labels are nothing but the name of the  Google Earth *path* file, which you assign. By slightly modifying `data_generation/point-based-samples/pytokml_csv_generator.ipynb` according to your use, you can create *csv* where first two columns correspond to lat/long pair and the third represent the *class* name which you assign to that *path* file.

This project includes the usage of VHR as well as Sentinel 2B imagery, Both these datasets undergo a similar process starting from samples creation to predictions. The VHR imagery is a proprietary dataset, which we had to purchase from Private Satellite Image providers. It is used in the project for comparison of the results with Sentinel Imagery.
